<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PenilaianAwalKeperawatanKebidanan extends Model
{
    public $timestamps = false;
    protected $table = "penilaian_awal_keperawatan_kebidanan";
    public $incrementing = false;
    protected $keyType = 'string';
    protected $primaryKey = 'no_rawat';
    protected $fillable = [
        'no_rawat',
        'tanggal',
        'informasi',
        'td',
        'nadi',
        'rr',
        'suhu',
        'gcs',
        'bb',
        'tb',
        'lila',
        'bmi',
        'tfu',
        'tbj',
        'letak',
        'presentasi',
        'penurunan',
        'his',
        'kekuatan',
        'lamanya',
        'bjj',
        'ket_bjj',
        'portio',
        'serviks',
        'ketuban',
        'hodge',
        'inspekulo',
        'ket_inspekulo',
        'ctg',
        'ket_ctg',
        'usg',
        'ket_usg',
        'lab',
        'ket_lab',
        'lakmus',
        'ket_lakmus',
        'panggul',
        'keluhan_utama',
        'umur',
        'lama',
        'banyaknya',
        'haid',
        'siklus',
        'ket_siklus',
        'ket_siklus1',
        'status',
        'kali',
        'usia1',
        'ket1',
        'usia2',
        'ket2',
        'usia3',
        'ket3',
        'hpht',
        'usia_kehamilan',
        'tp',
        'imunisasi',
        'ket_imunisasi',
        'g',
        'p',
        'a',
        'hidup',
        'ginekologi',
        'kebiasaan',
        'ket_kebiasaan',
        'kebiasaan1',
        'ket_kebiasaan1',
        'kebiasaan2',
        'ket_kebiasaan2',
        'kebiasaan3',
        'kb',
        'ket_kb',
        'komplikasi',
        'ket_komplikasi',
        'berhenti',
        'alasan',
        'alat_bantu',
        'ket_bantu',
        'prothesa',
        'ket_pro',
        'adl',
        'status_psiko',
        'ket_psiko',
        'hub_keluarga',
        'tinggal_dengan',
        'ket_tinggal',
        'ekonomi',
        'budaya',
        'ket_budaya',
        'edukasi',
        'ket_edukasi',
        'berjalan_a',
        'berjalan_b',
        'berjalan_c',
        'hasil',
        'lapor',
        'ket_lapor',
        'sg1',
        'nilai1',
        'sg2',
        'nilai2',
        'total_hasil',
        'nyeri',
        'provokes',
        'ket_provokes',
        'quality',
        'ket_quality',
        'lokasi',
        'menyebar',
        'skala_nyeri',
        'durasi',
        'nyeri_hilang',
        'ket_nyeri',
        'pada_dokter',
        'ket_dokter',
        'masalah',
        'tindakan',
        'nip'
    ];

    protected $hidden = ['nip'];
}
